backend:
  name: git-gateway
  branch: main # Pastikan sesuai dengan nama branch di GitHub Anda

media_folder: "images/uploads" # Folder tempat menyimpan gambar berita
public_folder: "/images/uploads"

collections:
  - name: "berita"
    label: "Berita"
    folder: "content/berita" # Folder tempat menyimpan file berita (dalam format .md)
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "date", widget: "datetime" }
      - { label: "Kategori", name: "category", widget: "select", options: ["Prestasi", "Kegiatan", "Informasi"] }
      - { label: "Isi Berita", name: "body", widget: "markdown" }